services:
  db:
    container_name: postgres-fsd
    image: postgres:14.5
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - db
    restart: unless-stopped
  amigoscode-api:
    container_name: amigoscode-api
    image: tjnewton/amigoscode-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8080:3000"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
  amigoscode-react:
    container_name: amigoscode-react
    image: tjnewton/amigoscode-react
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8080
    ports:
      - "3000:5173"
    depends_on:
      - amigoscode-api
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  postgres: